name: Code Quality

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: "6.0.x"

        - name: Restore Tools
          run: |
            dotnet tool install --global jetbrains.resharper.globaltools
            dotnet tool install --global nvika

        - name: Restore Packages
          run: dotnet restore

        - name: InspectCode
          run: jb inspectcode ${{github.workspace}}/DragonFruit.OnionFruit.Web.sln --output=${{github.workspace}}/inspectcodereport.xml --cachesDir=${{github.workspace}}/inspectcode --verbosity=WARN --no-build

        - name: NVika
          run: nvika parsereport "${{github.workspace}}/inspectcodereport.xml"