name: WebDeploy Package Generation

on:
  release:
    types: [ published ]

permissions:
  packages: read
  contents: write

jobs:  
  webdeploy-windows:
    runs-on: windows-latest
    
    env:
      OUTPUT_FILE_NAME: OnionFruit-Web-${{ github.event.release.tag_name }}.zip
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup GitHub NuGet
        run: dotnet nuget update source dragonfruit --username USERNAME --password ${{ github.token }} --store-password-in-clear-text

      - name: Build Server Package
        run: dotnet publish -c Release -r win-x64 --self-contained false -p:Version=${{ github.event.release.tag_name }} -p:PublishProfile=IISDeploy.pubxml -p:EnvironmentName=Production -p:ServerPublish=true DragonFruit.OnionFruit.Web

      - name: Archive Output
        run: Compress-Archive -Path .\DragonFruit.OnionFruit.Web\bin\publish\* -DestinationPath ${{ env.OUTPUT_FILE_NAME }}

      - name: Upload Deploy Package
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.OUTPUT_FILE_NAME }}