name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: windows-latest

    env:
      name: "DragonFruit.OnionFruit.Status"
      project: "DragonFruit.OnionFruit.Status\\DragonFruit.OnionFruit.Status.csproj"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PowerShell Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
        
      - name: Download Publish Script
        run: powershell Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dragonfruitnetwork/publish-script/main/nuget.ps1" -OutFile ".\nuget.ps1"

      - name: NuGet Build and Publish (Release)
        run: .\nuget.ps1 -TargetName $env:name -TargetProject $env:project -ApiKey ${{ secrets.NUGET_KEY }}
        if: "!github.event.release.prerelease"

      - name: Nuget Build and Publish (Beta)
        run: .\nuget.ps1 -TargetName $env:name -TargetProject $env:project -ApiKey ${{ secrets.NUGET_KEY }} -Suffix "-beta"
        if: "github.event.release.prerelease"

       
          
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (Release)
        uses: docker/build-push-action@v2
        if: "!github.event.release.prerelease"
        with:
          push: true
          context: .
          tags: dragonfruitdotnet/onionfruit-country-engine:latest
          file: ./DragonFruit.OnionFruit.Status.Generator/Dockerfile

      - name: Build and push (Beta)
        uses: docker/build-push-action@v2
        if: "github.event.release.prerelease"
        with:
          push: true
          context: .
          tags: dragonfruitdotnet/onionfruit-country-engine:beta
          file: ./DragonFruit.OnionFruit.Status.Generator/Dockerfile     