name: Test Run

on: [ pull_request, push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NuGet Restore
        run: |
          nuget locals all -clear
          nuget restore

      - name: Build
        run: |
          dotnet restore
          dotnet build -c Release
          
      - name: Test
        run: |
          cd DragonFruit.OnionFruit.Status.Tests
          dotnet run
