name: Test Run

on: [ pull_request, push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: NuGet Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release
          
      - name: Test
        run: |
          cd DragonFruit.OnionFruit.Status.Tests
          dotnet run
